name: Tests

on: [push, pull_request]

jobs:
  find-non-finishing-test:
    name: Find the test that causes timeout on GitHub actions
    
    strategy:
      matrix:
        test:
          - "tests/application/test_autodock.py"
          - "tests/application/test_dssp.py"
          - "tests/application/test_msa.py"
          - "tests/application/test_rnafold.py"
          - "tests/application/test_rnaplot.py"
          - "tests/application/test_tantan.py"
          - "tests/database/test_rcsb.py"
          - "tests/database/test_uniprot.py"
          - "tests/sequence/align/test_alignment.py"
          - "tests/sequence/align/test_banded.py"
          - "tests/sequence/align/test_kmeralphabet.py"
          - "tests/sequence/align/test_kmersimilarity.py"
          - "tests/sequence/align/test_kmertable.py"
          - "tests/sequence/align/test_localgapped.py"
          - "tests/sequence/align/test_localungapped.py"
          - "tests/sequence/align/test_matrix.py"
          - "tests/sequence/align/test_multiple.py"
          - "tests/sequence/align/test_pairwise.py"
          - "tests/sequence/align/test_statistics.py"
          - "tests/sequence/test_alphabet.py"
          - "tests/sequence/test_annotation.py"
          - "tests/sequence/test_codon.py"
          - "tests/sequence/test_fasta.py"
          - "tests/sequence/test_fastq.py"
          - "tests/sequence/test_genbank.py"
          - "tests/sequence/test_generalio.py"
          - "tests/sequence/test_gff.py"
          - "tests/sequence/test_graphics.py"
          - "tests/sequence/test_phylo.py"
          - "tests/sequence/test_profile.py"
          - "tests/sequence/test_search.py"
          - "tests/sequence/test_seqtypes.py"
          - "tests/sequence/test_sequence.py"
          - "tests/structure/test_atoms.py"
          - "tests/structure/test_basepairs.py"
          - "tests/structure/test_bonds.py"
          - "tests/structure/test_box.py"
          - "tests/structure/test_celllist.py"
          - "tests/structure/test_chains.py"
          - "tests/structure/test_charges.py"
          - "tests/structure/test_compare.py"
          - "tests/structure/test_density.py"
          - "tests/structure/test_dotbracket.py"
          - "tests/structure/test_filter.py"
          - "tests/structure/test_generalio.py"
          - "tests/structure/test_geometry.py"
          - "tests/structure/test_gro.py"
          - "tests/structure/test_hbond.py"
          - "tests/structure/test_info.py"
          - "tests/structure/test_integrity.py"
          - "tests/structure/test_mechanics.py"
          - "tests/structure/test_mmtf.py"
          - "tests/structure/test_mol.py"
          - "tests/structure/test_molecules.py"
          - "tests/structure/test_npz.py"
          - "tests/structure/test_pdb.py"
          - "tests/structure/test_pdbqt.py"
          - "tests/structure/test_pdbx.py"
          - "tests/structure/test_pseudoknots.py"
          - "tests/structure/test_rdf.py"
          - "tests/structure/test_residues.py"
          - "tests/structure/test_sasa.py"
          - "tests/structure/test_sse.py"
          - "tests/structure/test_superimpose.py"
          - "tests/structure/test_trajectory.py"
          - "tests/structure/test_transform.py"
          - "tests/test_doctest.py"
          - "tests/test_init.py"
          - "tests/test_modname.py"
          - "tests/test_repr.py"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: biotite-dev
          environment-file: environment.yml
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,defaults
      - name: Building distribution
        run: python setup.py bdist_wheel
      - name: Installing distribution
        run: pip install .//dist//*.whl
      - name: Testing code
        run: pytest ${{ matrix.test }}
