name: Tests

on: [push, pull_request]

jobs:
  find-non-finishing-test:
    name: Find the test that causes timeout on GitHub actions
    
    strategy:
      fail-fast: false
      matrix:
        test:
          - "tests/test_doctest.py::test_doctest[biotite.sequence-context_package_names1]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.align-context_package_names2]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.phylo-context_package_names3]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.graphics-context_package_names4]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.io-context_package_names5]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.io.fasta-context_package_names6]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.io.fastq-context_package_names7]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.io.genbank-context_package_names8]"
          - "tests/test_doctest.py::test_doctest[biotite.sequence.io.gff-context_package_names9]"
          - "tests/test_doctest.py::test_doctest[biotite.structure-context_package_names10]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.graphics-context_package_names11]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io-context_package_names12]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.pdb-context_package_names13]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.pdbx-context_package_names14]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.pdbqt-context_package_names15]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.npz-context_package_names16]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.mmtf-context_package_names17]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.io.mol-context_package_names18]"
          - "tests/test_doctest.py::test_doctest[biotite.structure.info-context_package_names19]"
          - "tests/test_doctest.py::test_doctest[biotite.database.entrez-context_package_names20]"
          - "tests/test_doctest.py::test_doctest[biotite.database.rcsb-context_package_names21]"
          - "tests/test_doctest.py::test_doctest[biotite.database.uniprot-context_package_names22]"
          - "tests/test_doctest.py::test_doctest[biotite.application-context_package_names23]"
          - "tests/test_doctest.py::test_doctest[biotite.application.blast-context_package_names24]"
          - "tests/test_doctest.py::test_doctest[biotite.application.clustalo-context_package_names25]"
          - "tests/test_doctest.py::test_doctest[biotite.application.mafft-context_package_names26]"
          - "tests/test_doctest.py::test_doctest[biotite.application.sra-context_package_names27]"
          - "tests/test_doctest.py::test_doctest[biotite.application.tantan-context_package_names28]"
          - "tests/test_doctest.py::test_doctest[biotite.application.viennarna-context_package_names29]"
          - "tests/test_doctest.py::test_doctest[biotite.application.dssp-context_package_names30]"
          - "tests/test_doctest.py::test_doctest[biotite.application.autodock-context_package_names31]"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: biotite-dev
          environment-file: environment.yml
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,defaults
      - name: Building distribution
        run: python setup.py bdist_wheel
      - name: Installing distribution
        run: pip install .//dist//*.whl
      - name: Testing code
        run: pytest --ignore ${{ matrix.test }} "tests/test_doctest.py"
